-- =============================================================================
-- RATIONALIZATION — scores and the asset profile (compute; safe to re-run)
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE SCHEMA RATIONALIZATION;

-- ----------------------------------------------------------- ASSET_SCORE ----
CREATE OR REPLACE FUNCTION RATIONALIZATION.POLICY(K TEXT)
RETURNS NUMBER(12,4)
AS $$ SELECT POLICY_VALUE FROM RATIONALIZATION.SCORING_POLICY WHERE POLICY_KEY = K $$;

CREATE OR REPLACE TABLE ASSET_SCORE AS
WITH p AS (
    SELECT PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY LN(1 + VIEWS_90))   AS P95_LOG_VIEWS,
           PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY LN(1 + VIEWERS_90)) AS P95_LOG_VIEWERS
    FROM CONFORMED.USAGE_SUMMARY
), base AS (
    SELECT a.ASSET_ID,
           us.VIEWS_90, us.VIEWERS_90, us.EXEC_VIEWERS_365, us.VIEWER_DEPARTMENTS_365,
           d.SUBSCRIPTION_COUNT, d.EXEC_SUBSCRIBER_COUNT, d.REFRESH_FAILURE_RATE,
           a.IS_CERTIFIED,
           EXISTS (SELECT 1 FROM V_REGULATORY_MATCH r WHERE r.ASSET_ID = a.ASSET_ID) AS IS_REGULATORY,
           c.CALC_FIELD_COUNT, c.LOD_COUNT, c.TIME_INTEL_COUNT, c.TABLE_CALC_COUNT, c.CONTEXT_COUNT, c.ITERATOR_COUNT,
           c.PARAMETER_COUNT, c.SPECIAL_COUNT, c.VENDOR_DEFINED_COUNT, c.HAS_CUSTOM_SQL, c.SOURCE_TABLE_COUNT, c.SOURCE_SYSTEM_COUNT,
           c.COMPONENT_COUNT, c.HAS_UNMANAGED_SOURCE, c.HAS_DECOMMISSIONED_SOURCE, c.HAS_UNCATALOGED_SOURCE,
           LEAST(100, 60 * LN(1 + us.VIEWS_90) / NULLIF(p.P95_LOG_VIEWS, 0)
                    + 40 * LN(1 + us.VIEWERS_90) / NULLIF(p.P95_LOG_VIEWERS, 0)) AS USAGE_SCORE_RAW,
           -- complexity points, weighted by how badly each construct converts
             c.CALC_FIELD_COUNT * 1.0 + c.LOD_COUNT * 4 + c.TIME_INTEL_COUNT * 4 + c.TABLE_CALC_COUNT * 3
           + c.CONTEXT_COUNT * 3 + c.ITERATOR_COUNT * 2 + c.PARAMETER_COUNT * 2 + c.SPECIAL_COUNT * 6 + c.VENDOR_DEFINED_COUNT * 5
           + IFF(c.HAS_CUSTOM_SQL, 5, 0) + GREATEST(0, c.SOURCE_TABLE_COUNT - 1) * 2
           + IFF(c.SOURCE_SYSTEM_COUNT > 1, 4, 0) + c.COMPONENT_COUNT * 1.5 + IFF(c.HAS_UNMANAGED_SOURCE, 3, 0) AS COMPLEXITY_POINTS
    FROM CONFORMED.ASSET a
    JOIN CONFORMED.USAGE_SUMMARY us ON us.ASSET_ID = a.ASSET_ID
    JOIN CONFORMED.ASSET_DELIVERY d ON d.ASSET_ID = a.ASSET_ID
    JOIN CONFORMED.ASSET_COMPLEXITY c ON c.ASSET_ID = a.ASSET_ID
    CROSS JOIN p
)
SELECT ASSET_ID,
       ROUND(COALESCE(USAGE_SCORE_RAW, 0), 1) AS USAGE_SCORE,
       LEAST(100,
             IFF(EXEC_VIEWERS_365 > 0, 30, 0) + IFF(SUBSCRIPTION_COUNT > 0, 15, 0) + IFF(EXEC_SUBSCRIBER_COUNT > 0, 15, 0)
           + IFF(IS_REGULATORY, 30, 0) + IFF(IS_CERTIFIED, 10, 0) + LEAST(10, VIEWER_DEPARTMENTS_365 * 2)) AS CRITICALITY_SCORE,
       ROUND(COMPLEXITY_POINTS, 1) AS COMPLEXITY_POINTS,
       CASE WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_S_MAX') THEN 'S'
            WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_M_MAX') THEN 'M'
            WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_L_MAX') THEN 'L' ELSE 'XL' END AS COMPLEXITY_BAND,
       GREATEST(0, 100 - IFF(HAS_DECOMMISSIONED_SOURCE, 60, 0) - IFF(HAS_UNMANAGED_SOURCE, 25, 0)
                   - IFF(HAS_UNCATALOGED_SOURCE, 20, 0) - IFF(COALESCE(REFRESH_FAILURE_RATE, 0) > 0.5, 40, 0)) AS DATA_HEALTH_SCORE,
       IS_REGULATORY,
       CASE WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_S_MAX') THEN POLICY('EFFORT_HOURS_S')
            WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_M_MAX') THEN POLICY('EFFORT_HOURS_M')
            WHEN COMPLEXITY_POINTS < POLICY('COMPLEXITY_BAND_L_MAX') THEN POLICY('EFFORT_HOURS_L')
            ELSE POLICY('EFFORT_HOURS_XL') END AS CONVERSION_HOURS_BASE
FROM base;

-- ---------------------------------------------------------- ASSET_PROFILE ---
-- The one wide row per asset that the rules are written against. A rule
-- condition can reference any column here and nothing else.
CREATE OR REPLACE VIEW V_ASSET_PROFILE AS
SELECT a.ASSET_ID, a.PLATFORM, a.ASSET_KIND, a.TITLE, a.TITLE_KEY, a.CONTAINER_PATH,
       a.IS_PERSONAL_SPACE, a.IS_SANDBOX, a.OWNER_EMAIL, a.OWNER_DEPARTMENT, a.OWNER_IS_ACTIVE, a.OWNER_IS_DEVELOPER,
       a.CREATED_AT, a.MODIFIED_AT, a.IS_CERTIFIED, a.COMPONENT_COUNT,
       DATEDIFF(day, a.CREATED_AT, INVENTORY.AS_OF_DATE())  AS AGE_DAYS,
       REGEXP_LIKE(LOWER(a.TITLE), '.*(copy of|\\(copy\\)| - copy|\\bv[0-9]+\\b|\\(final\\)|\\bfinal\\b|\\bdraft\\b|\\btest\\b|\\bold\\b|\\(old\\)|\\(2\\)|backup|do not (use|delete)|''s version).*') AS HAS_COPY_MARKER,
       us.VIEWS_30, us.VIEWS_90, us.VIEWS_365, us.VIEWS_PRIOR_90, us.VIEWS_TOTAL, us.EXPORTS_90,
       us.VIEWERS_90, us.VIEWERS_365, us.EXEC_VIEWERS_365, us.VIEWER_DEPARTMENTS_365,
       us.DEVELOPER_VIEW_SHARE, us.OWNER_VIEW_SHARE, us.LAST_VIEWED_DATE, us.DAYS_SINCE_LAST_VIEW,
       us.TREND_RATIO_90, us.HAS_EMBEDDED_USAGE,
       d.SUBSCRIPTION_COUNT, d.EXEC_SUBSCRIBER_COUNT, d.INACTIVE_SUBSCRIBER_COUNT, d.DELIVERY_DESTINATION,
       d.REFRESH_RUNS_90, d.REFRESH_FAILURES_90, d.REFRESH_FAILURE_RATE, d.IS_SCHEDULED,
       c.BASE_FIELD_COUNT, c.CALC_FIELD_COUNT, c.LOD_COUNT, c.TIME_INTEL_COUNT, c.TABLE_CALC_COUNT, c.CONTEXT_COUNT,
       c.ITERATOR_COUNT, c.PARAMETER_COUNT, c.SPECIAL_COUNT, c.VENDOR_DEFINED_COUNT, c.SOURCE_TABLE_COUNT, c.SOURCE_SYSTEM_COUNT,
       c.HAS_CUSTOM_SQL, c.HAS_DECOMMISSIONED_SOURCE, c.HAS_UNMANAGED_SOURCE, c.HAS_UNCATALOGED_SOURCE, c.HAS_PARAMETER,
       s.USAGE_SCORE, s.CRITICALITY_SCORE, s.COMPLEXITY_POINTS, s.COMPLEXITY_BAND, s.DATA_HEALTH_SCORE,
       s.IS_REGULATORY, s.CONVERSION_HOURS_BASE,
       dc.CLUSTER_ID, dc.CLUSTER_SIZE, COALESCE(dc.IS_CANONICAL, FALSE) AS IS_CLUSTER_CANONICAL,
       dc.CANONICAL_ASSET_ID, dc.CANONICAL_TITLE,
       sg.SUBJECT_AREA, sg.ENTITIES,
       (SELECT LISTAGG(r.OBLIGATION, '; ') FROM V_REGULATORY_MATCH r WHERE r.ASSET_ID = a.ASSET_ID) AS REGULATORY_OBLIGATIONS
FROM CONFORMED.ASSET a
JOIN CONFORMED.USAGE_SUMMARY us   ON us.ASSET_ID = a.ASSET_ID
JOIN CONFORMED.ASSET_DELIVERY d   ON d.ASSET_ID = a.ASSET_ID
JOIN CONFORMED.ASSET_COMPLEXITY c ON c.ASSET_ID = a.ASSET_ID
JOIN ASSET_SCORE s                ON s.ASSET_ID = a.ASSET_ID
JOIN CONFORMED.ASSET_SIGNATURE sg ON sg.ASSET_ID = a.ASSET_ID
LEFT JOIN CONFORMED.DUPLICATE_CLUSTER dc ON dc.ASSET_ID = a.ASSET_ID;
