-- =============================================================================
-- RATIONALIZATION — the rule engine (compute; safe to re-run)
-- -----------------------------------------------------------------------------
-- Rules live in DISPOSITION_RULE (seeded once, edited by the engagement). This
-- file defines the engine, runs it, and builds the final-disposition views.
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE SCHEMA RATIONALIZATION;

-- ---------------------------------------------------------- the engine ------
CREATE TABLE IF NOT EXISTS RATIONALIZATION_RUN (
    RUN_ID NUMBER IDENTITY, STARTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), RUN_BY TEXT DEFAULT CURRENT_USER(),
    ASSET_COUNT NUMBER, NOTE TEXT
);

CREATE TABLE IF NOT EXISTS ASSET_DISPOSITION (
    RUN_ID            NUMBER,
    ASSET_ID          TEXT,
    DISPOSITION       TEXT,
    RULE_ID           TEXT,
    CONFIDENCE        TEXT,
    REASON            TEXT,
    CONSOLIDATE_INTO  TEXT,
    EVIDENCE          OBJECT,
    EFFORT_HOURS      NUMBER(10,1),
    ASSIGNED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE RATIONALIZATION.SP_RUN_RATIONALIZATION(NOTE TEXT DEFAULT NULL)
RETURNS TEXT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    run_id NUMBER;
    assigned NUMBER := 0;
    rule_cursor CURSOR FOR
        SELECT RULE_ID, DISPOSITION, CONFIDENCE, CONDITION_SQL, REASON_SQL
        FROM RATIONALIZATION.DISPOSITION_RULE WHERE IS_ENABLED ORDER BY PRIORITY;
    v_rule_id TEXT; v_disp TEXT; v_conf TEXT; v_cond TEXT; v_reason TEXT; stmt TEXT;
BEGIN
    INSERT INTO RATIONALIZATION.RATIONALIZATION_RUN (ASSET_COUNT, NOTE)
        SELECT COUNT(*), :NOTE FROM CONFORMED.ASSET;
    SELECT MAX(RUN_ID) INTO :run_id FROM RATIONALIZATION.RATIONALIZATION_RUN;

    FOR r IN rule_cursor DO
        v_rule_id := r.RULE_ID; v_disp := r.DISPOSITION; v_conf := r.CONFIDENCE;
        v_cond := r.CONDITION_SQL; v_reason := r.REASON_SQL;
        stmt := 'INSERT INTO RATIONALIZATION.ASSET_DISPOSITION '
             || '(RUN_ID, ASSET_ID, DISPOSITION, RULE_ID, CONFIDENCE, REASON, CONSOLIDATE_INTO, EVIDENCE, EFFORT_HOURS) '
             || 'SELECT ' || run_id || ', p.ASSET_ID, ''' || v_disp || ''', ''' || v_rule_id || ''', ''' || v_conf || ''', '
             || '(' || v_reason || '), '
             || IFF(v_disp = 'CONSOLIDATE', 'p.CANONICAL_ASSET_ID', 'NULL') || ', '
             || 'OBJECT_CONSTRUCT(''views_90'', p.VIEWS_90, ''views_365'', p.VIEWS_365, ''viewers_90'', p.VIEWERS_90, '
             || '''exec_viewers_365'', p.EXEC_VIEWERS_365, ''days_since_last_view'', p.DAYS_SINCE_LAST_VIEW, '
             || '''subscriptions'', p.SUBSCRIPTION_COUNT, ''trend_ratio_90'', p.TREND_RATIO_90, '
             || '''complexity_band'', p.COMPLEXITY_BAND, ''complexity_points'', p.COMPLEXITY_POINTS, '
             || '''data_health'', p.DATA_HEALTH_SCORE, ''cluster_id'', p.CLUSTER_ID, ''cluster_size'', p.CLUSTER_SIZE, '
             || '''decommissioned_source'', p.HAS_DECOMMISSIONED_SOURCE, ''regulatory'', p.IS_REGULATORY), '
             || CASE v_disp
                  WHEN 'MIGRATE'      THEN 'p.CONVERSION_HOURS_BASE * (1 + RATIONALIZATION.POLICY(''VALIDATION_SHARE''))'
                  WHEN 'REBUILD'      THEN 'p.CONVERSION_HOURS_BASE * RATIONALIZATION.POLICY(''REBUILD_MULTIPLIER'') * (1 + RATIONALIZATION.POLICY(''VALIDATION_SHARE''))'
                  WHEN 'SELF_SERVICE' THEN 'RATIONALIZATION.POLICY(''SELF_SERVICE_HOURS'')'
                  WHEN 'INVESTIGATE'  THEN 'p.CONVERSION_HOURS_BASE * 0.5'
                  WHEN 'CONSOLIDATE'  THEN 'RATIONALIZATION.POLICY(''CONSOLIDATE_HOURS'')'
                  ELSE '0' END || ' '
             || 'FROM RATIONALIZATION.V_ASSET_PROFILE p '
             || 'WHERE (' || v_cond || ') '
             || 'AND NOT EXISTS (SELECT 1 FROM RATIONALIZATION.ASSET_DISPOSITION d WHERE d.RUN_ID = ' || run_id || ' AND d.ASSET_ID = p.ASSET_ID)';
        EXECUTE IMMEDIATE :stmt;
    END FOR;
    SELECT COUNT(*) INTO :assigned FROM RATIONALIZATION.ASSET_DISPOSITION WHERE RUN_ID = :run_id;
    -- keep the last five runs so a re-run is comparable but the table does not grow without bound
    DELETE FROM RATIONALIZATION.ASSET_DISPOSITION WHERE RUN_ID < :run_id - 4;
    DELETE FROM RATIONALIZATION.RATIONALIZATION_RUN WHERE RUN_ID < :run_id - 4;
    RETURN 'run ' || run_id || ': ' || assigned || ' assets assigned';
END;
$$;

CALL RATIONALIZATION.SP_RUN_RATIONALIZATION('Initial run on the full-estate extract');

-- ------------------------------------------------- final disposition --------
CREATE OR REPLACE VIEW V_FINAL_DISPOSITION AS
WITH latest AS (SELECT MAX(RUN_ID) RUN_ID FROM RATIONALIZATION_RUN),
     rev AS (
        SELECT ASSET_ID, REVIEWER, DECISION, FINAL_DISPOSITION, NOTE, DECIDED_AT
        FROM DISPOSITION_REVIEW QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY DECIDED_AT DESC) = 1
     )
SELECT d.ASSET_ID, p.PLATFORM, p.ASSET_KIND, p.TITLE, p.OWNER_EMAIL, p.OWNER_DEPARTMENT, p.SUBJECT_AREA,
       d.DISPOSITION                                   AS RECOMMENDED_DISPOSITION,
       d.RULE_ID, r.RULE_NAME, d.CONFIDENCE, d.REASON, d.CONSOLIDATE_INTO, d.EVIDENCE,
       COALESCE(rv.FINAL_DISPOSITION, d.DISPOSITION)   AS FINAL_DISPOSITION,
       CASE WHEN rv.ASSET_ID IS NULL THEN 'PENDING' ELSE rv.DECISION END AS REVIEW_STATUS,
       rv.REVIEWER, rv.NOTE AS REVIEW_NOTE, rv.DECIDED_AT,
       COALESCE(rv.FINAL_DISPOSITION, d.DISPOSITION) IN ('MIGRATE', 'REBUILD', 'SELF_SERVICE') AS IS_SURVIVING,
       CASE COALESCE(rv.FINAL_DISPOSITION, d.DISPOSITION)
            WHEN 'MIGRATE'      THEN p.CONVERSION_HOURS_BASE * (1 + POLICY('VALIDATION_SHARE'))
            WHEN 'REBUILD'      THEN p.CONVERSION_HOURS_BASE * POLICY('REBUILD_MULTIPLIER') * (1 + POLICY('VALIDATION_SHARE'))
            WHEN 'SELF_SERVICE' THEN POLICY('SELF_SERVICE_HOURS')
            WHEN 'INVESTIGATE'  THEN p.CONVERSION_HOURS_BASE * 0.5
            WHEN 'CONSOLIDATE'  THEN POLICY('CONSOLIDATE_HOURS')
            ELSE 0 END                                  AS EFFORT_HOURS,
       p.CONVERSION_HOURS_BASE * (1 + POLICY('VALIDATION_SHARE')) AS EFFORT_HOURS_IF_MIGRATED_AS_IS,
       p.USAGE_SCORE, p.CRITICALITY_SCORE, p.COMPLEXITY_BAND, p.COMPLEXITY_POINTS, p.DATA_HEALTH_SCORE,
       p.VIEWS_90, p.VIEWS_365, p.VIEWERS_90, p.EXEC_VIEWERS_365, p.DAYS_SINCE_LAST_VIEW, p.SUBSCRIPTION_COUNT,
       p.CLUSTER_ID, p.CLUSTER_SIZE, p.IS_CLUSTER_CANONICAL, p.IS_REGULATORY, p.HAS_DECOMMISSIONED_SOURCE,
       p.ENTITIES
FROM ASSET_DISPOSITION d
JOIN latest l ON l.RUN_ID = d.RUN_ID
JOIN V_ASSET_PROFILE p ON p.ASSET_ID = d.ASSET_ID
JOIN DISPOSITION_RULE r ON r.RULE_ID = d.RULE_ID
LEFT JOIN rev rv ON rv.ASSET_ID = d.ASSET_ID;

CREATE OR REPLACE VIEW V_RATIONALIZATION_SUMMARY AS
SELECT FINAL_DISPOSITION,
       COUNT(*)                                        AS ASSETS,
       ROUND(COUNT(*) / SUM(COUNT(*)) OVER () * 100, 1) AS PCT_OF_ESTATE,
       SUM(VIEWS_365)                                  AS VIEWS_365,
       ROUND(SUM(VIEWS_365) / SUM(SUM(VIEWS_365)) OVER () * 100, 1) AS PCT_OF_VIEWS,
       ROUND(SUM(EFFORT_HOURS))                        AS EFFORT_HOURS,
       ROUND(SUM(EFFORT_HOURS_IF_MIGRATED_AS_IS))      AS EFFORT_HOURS_IF_MIGRATED_AS_IS,
       COUNT_IF(REVIEW_STATUS <> 'PENDING')            AS REVIEWED
FROM V_FINAL_DISPOSITION
GROUP BY 1;

CREATE OR REPLACE VIEW V_RULE_HITS AS
SELECT r.PRIORITY, r.RULE_ID, r.RULE_NAME, r.DISPOSITION, r.CONFIDENCE,
       COUNT(d.ASSET_ID) AS ASSETS, SUM(d.EFFORT_HOURS) AS EFFORT_HOURS,
       COUNT_IF(f.REVIEW_STATUS = 'OVERRIDE') AS OVERRIDDEN
FROM DISPOSITION_RULE r
LEFT JOIN ASSET_DISPOSITION d ON d.RULE_ID = r.RULE_ID AND d.RUN_ID = (SELECT MAX(RUN_ID) FROM RATIONALIZATION_RUN)
LEFT JOIN V_FINAL_DISPOSITION f ON f.ASSET_ID = d.ASSET_ID
GROUP BY 1, 2, 3, 4, 5 ORDER BY 1;
