-- =============================================================================
-- TARGET_MODEL — the future-state model, derived from what survives
-- -----------------------------------------------------------------------------
-- This is the deliverable the ingestion and data teams build to. It is not
-- designed from a whiteboard; it is derived from the lineage of the assets
-- that survived rationalization: which entities they read, which attributes
-- they use, which metrics they compute (and how many ways). Every entity in
-- the backlog can say which reports it unblocks, and every metric can show
-- the definitions it has to reconcile.
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE SCHEMA TARGET_MODEL;

-- Surviving assets, plus INVESTIGATE (they may survive; the model should be
-- ready for them) — everything else is excluded on purpose. A retired report
-- does not get to put an attribute into the target model.
CREATE OR REPLACE VIEW V_MODEL_DRIVING_ASSET AS
SELECT ASSET_ID, FINAL_DISPOSITION, SUBJECT_AREA, VIEWS_365, EXEC_VIEWERS_365, IS_REGULATORY,
       CRITICALITY_SCORE, FINAL_DISPOSITION IN ('MIGRATE', 'REBUILD', 'SELF_SERVICE') AS IS_SURVIVING
FROM RATIONALIZATION.V_FINAL_DISPOSITION
WHERE FINAL_DISPOSITION IN ('MIGRATE', 'REBUILD', 'SELF_SERVICE', 'INVESTIGATE');

-- ------------------------------------------------------------- ENTITY -------
CREATE OR REPLACE TABLE ENTITY AS
WITH use AS (
    SELECT l.CONFORMED_ENTITY, l.ENTITY_ROLE, l.SUBJECT_AREA AS CATALOG_SUBJECT_AREA,
           a.ASSET_ID, a.IS_SURVIVING, a.VIEWS_365, a.EXEC_VIEWERS_365, a.IS_REGULATORY, a.SUBJECT_AREA AS ASSET_SUBJECT_AREA,
           l.SOURCE_DATABASE, l.SOURCE_SCHEMA, l.SOURCE_TABLE, l.IS_DECOMMISSIONED,
           -- a hosted vendor domain (MedeAnalytics and similar) ends with the contract:
           -- it is lineage, not a source the target model can be built from
           COALESCE(c.SYSTEM_FAMILY ILIKE '%(hosted)%', FALSE) AS IS_HOSTED_VENDOR
    FROM CONFORMED.ASSET_LINEAGE l
    JOIN V_MODEL_DRIVING_ASSET a ON a.ASSET_ID = l.ASSET_ID
    LEFT JOIN INVENTORY.SOURCE_SYSTEM_CATALOG c ON c.SOURCE_DATABASE = l.SOURCE_DATABASE AND UPPER(c.SOURCE_TABLE) = UPPER(l.SOURCE_TABLE)
    WHERE l.CONFORMED_ENTITY IS NOT NULL
), agg AS (
    SELECT CONFORMED_ENTITY, MAX(ENTITY_ROLE) AS ENTITY_ROLE, MODE(CATALOG_SUBJECT_AREA) AS SUBJECT_AREA,
           COUNT(DISTINCT IFF(IS_SURVIVING, ASSET_ID, NULL))                AS SURVIVING_ASSETS,
           COUNT(DISTINCT ASSET_ID)                                         AS DEPENDING_ASSETS,
           COUNT(DISTINCT IFF(EXEC_VIEWERS_365 > 0, ASSET_ID, NULL))        AS EXEC_ASSETS,
           COUNT(DISTINCT IFF(IS_REGULATORY, ASSET_ID, NULL))               AS REGULATORY_ASSETS,
           COUNT(DISTINCT ASSET_SUBJECT_AREA)                               AS SUBJECT_AREAS_USING,
           ARRAY_AGG(DISTINCT OBJECT_CONSTRUCT('source', SOURCE_DATABASE || '.' || SOURCE_SCHEMA || '.' || SOURCE_TABLE,
                                               'decommissioned', IS_DECOMMISSIONED, 'hosted_vendor', IS_HOSTED_VENDOR)) AS SOURCE_TABLES,
           BOOLAND_AGG(IS_DECOMMISSIONED)                                   AS ONLY_DECOMMISSIONED_SOURCES,
           BOOLAND_AGG(IS_DECOMMISSIONED OR IS_HOSTED_VENDOR)               AS NO_OWNED_LIVE_SOURCE,
           BOOLOR_AGG(IS_HOSTED_VENDOR)                                     AS HAS_HOSTED_VENDOR_SOURCE,
           BOOLOR_AGG(IS_DECOMMISSIONED)                                    AS ANY_DECOMMISSIONED_SOURCE,
           BOOLOR_AGG(SOURCE_DATABASE = 'SHAREPOINT')                       AS HAS_SPREADSHEET_SOURCE,
           BOOLAND_AGG(SOURCE_DATABASE = 'SHAREPOINT')                      AS ONLY_SPREADSHEET_SOURCES
    FROM use GROUP BY 1
)
SELECT a.CONFORMED_ENTITY AS ENTITY_NAME, a.ENTITY_ROLE, a.SUBJECT_AREA,
       (SELECT MIN(GRAIN) FROM INVENTORY.SOURCE_SYSTEM_CATALOG c WHERE c.CONFORMED_ENTITY = a.CONFORMED_ENTITY AND NOT c.IS_DECOMMISSIONED) AS GRAIN,
       a.SURVIVING_ASSETS, a.DEPENDING_ASSETS, a.EXEC_ASSETS, a.REGULATORY_ASSETS, a.SUBJECT_AREAS_USING,
       a.SUBJECT_AREAS_USING >= 2 AS IS_SHARED,
       a.SOURCE_TABLES, a.ONLY_DECOMMISSIONED_SOURCES, a.ANY_DECOMMISSIONED_SOURCE, a.HAS_SPREADSHEET_SOURCE,
       a.HAS_HOSTED_VENDOR_SOURCE,
       CASE WHEN a.ONLY_DECOMMISSIONED_SOURCES THEN 'NEEDS_NEW_SOURCE'
            WHEN a.NO_OWNED_LIVE_SOURCE THEN 'NEEDS_SYSTEM_OF_RECORD'
            WHEN a.ONLY_SPREADSHEET_SOURCES OR (a.HAS_SPREADSHEET_SOURCE AND a.ENTITY_ROLE = 'FACT') THEN 'NEEDS_SYSTEM_OF_RECORD'
            ELSE 'SOURCE_AVAILABLE' END AS SOURCE_STATUS,
       COALESCE((SELECT MIN(p.WAVE_NO) FROM RATIONALIZATION.V_SUBJECT_AREA_ENTITIES e
                 JOIN RATIONALIZATION.SUBJECT_AREA_PRIORITY p ON p.SUBJECT_AREA = e.SUBJECT_AREA
                 WHERE e.CONFORMED_ENTITY = a.CONFORMED_ENTITY), RATIONALIZATION.POLICY('WAVE_COUNT')) AS FIRST_WAVE_NEEDED,
       IFF(a.SUBJECT_AREAS_USING >= 2 AND a.ENTITY_ROLE = 'DIM', 0, NULL) AS FOUNDATION_WAVE
FROM agg a;

UPDATE ENTITY SET FIRST_WAVE_NEEDED = 0 WHERE FOUNDATION_WAVE = 0;

-- --------------------------------------------------------- ATTRIBUTE --------
CREATE OR REPLACE TABLE ENTITY_ATTRIBUTE AS
SELECT l.CONFORMED_ENTITY AS ENTITY_NAME, l.ATTRIBUTE_KEY AS ATTRIBUTE_NAME,
       COUNT(DISTINCT l.ASSET_ID)                                   AS REFERENCING_ASSETS,
       COUNT(DISTINCT IFF(a.IS_SURVIVING, l.ASSET_ID, NULL))        AS SURVIVING_ASSETS,
       ARRAY_AGG(DISTINCT l.SOURCE_DATABASE || '.' || l.SOURCE_SCHEMA || '.' || l.SOURCE_TABLE || '.' || l.SOURCE_COLUMN) AS SOURCE_COLUMNS,
       BOOLOR_AGG(NOT l.IS_DECOMMISSIONED AND l.SOURCE_DATABASE NOT IN ('SHAREPOINT', 'MEDE_PLATFORM')) AS HAS_LIVE_SOURCE,
       CASE WHEN l.ATTRIBUTE_KEY LIKE '%\\_ID' ESCAPE '\\' OR l.ATTRIBUTE_KEY IN ('MRN', 'NPI', 'PO_NUMBER', 'REQ_NUMBER', 'ACCOUNT', 'ACCOUNTING_UNIT', 'COMPANY') THEN 'KEY'
            WHEN l.ATTRIBUTE_KEY LIKE '%\\_FLAG' ESCAPE '\\' OR l.ATTRIBUTE_KEY LIKE 'IS\\_%' ESCAPE '\\' THEN 'FLAG'
            WHEN l.ATTRIBUTE_KEY LIKE '%DATETIME%' OR l.ATTRIBUTE_KEY LIKE '%\\_TIME' ESCAPE '\\' OR l.ATTRIBUTE_KEY LIKE '%\\_START' ESCAPE '\\' OR l.ATTRIBUTE_KEY LIKE '%\\_END' ESCAPE '\\' THEN 'TIMESTAMP'
            WHEN l.ATTRIBUTE_KEY LIKE '%DATE%' OR l.ATTRIBUTE_KEY LIKE '%MONTH' THEN 'DATE'
            WHEN REGEXP_LIKE(l.ATTRIBUTE_KEY, '.*(AMOUNT|COST|BALANCE|CHARGES|PAYMENTS|ADJUSTMENTS|LIABILITY|PAY|RATE|PREMIUM|SCORE|VALUE).*') THEN 'AMOUNT'
            WHEN REGEXP_LIKE(l.ATTRIBUTE_KEY, '.*(COUNT|DAYS|MINUTES|HOURS|UNITS|QUANTITY|CENSUS|BEDS|ADMISSIONS|DISCHARGES|TRANSFERS|LOS|FTE|LEVEL|NUMBER|LINE).*') THEN 'MEASURE'
            ELSE 'ATTRIBUTE' END                                        AS ATTRIBUTE_CLASS,
       MIN(w.WAVE_NO)                                               AS FIRST_WAVE_NEEDED
FROM CONFORMED.ASSET_LINEAGE l
JOIN V_MODEL_DRIVING_ASSET a ON a.ASSET_ID = l.ASSET_ID
LEFT JOIN RATIONALIZATION.V_ASSET_WAVE w ON w.ASSET_ID = l.ASSET_ID
WHERE l.CONFORMED_ENTITY IS NOT NULL
GROUP BY 1, 2;

-- Snowflake type for each attribute class, used by the DDL generator.
CREATE OR REPLACE FUNCTION TARGET_MODEL.ATTRIBUTE_TYPE(CLS TEXT)
RETURNS TEXT
AS $$
  CASE CLS WHEN 'KEY' THEN 'TEXT' WHEN 'FLAG' THEN 'BOOLEAN' WHEN 'TIMESTAMP' THEN 'TIMESTAMP_NTZ'
           WHEN 'DATE' THEN 'DATE' WHEN 'AMOUNT' THEN 'NUMBER(18,2)' WHEN 'MEASURE' THEN 'NUMBER(12,2)' ELSE 'TEXT' END
$$;

-- ------------------------------------------------------------ METRIC --------
-- Every calculated measure in a surviving asset, grouped by normalized name.
-- VARIANT_COUNT > 1 is the finding: one business term, several formulas.
CREATE OR REPLACE TABLE METRIC_VARIANT AS
SELECT f.FIELD_NAME_KEY, f.EXPRESSION_LANGUAGE, f.EXPRESSION, f.COMPLEXITY_TAG,
       COUNT(DISTINCT f.ASSET_ID)                       AS ASSET_COUNT,
       SUM(a.VIEWS_365)                                 AS VIEWS_365,
       MIN(f.ASSET_ID)                                  AS SAMPLE_ASSET_ID,
       MODE(f.FIELD_NAME)                               AS FIELD_NAME
FROM CONFORMED.ASSET_FIELD f
JOIN V_MODEL_DRIVING_ASSET a ON a.ASSET_ID = f.ASSET_ID
WHERE f.FIELD_KIND = 'CALCULATED' AND f.ROLE = 'MEASURE' AND f.EXPRESSION IS NOT NULL
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE TABLE METRIC AS
WITH g AS (
    SELECT FIELD_NAME_KEY,
           MODE(FIELD_NAME)                                    AS METRIC_NAME,
           COUNT(*)                                            AS VARIANT_COUNT,
           COUNT(DISTINCT EXPRESSION_LANGUAGE)                 AS LANGUAGE_COUNT,
           LISTAGG(DISTINCT EXPRESSION_LANGUAGE, ', ')         AS LANGUAGES,
           SUM(ASSET_COUNT)                                    AS ASSET_COUNT,
           SUM(VIEWS_365)                                      AS VIEWS_365,
           MAX_BY(EXPRESSION, ASSET_COUNT)                     AS DOMINANT_EXPRESSION,
           MAX_BY(EXPRESSION_LANGUAGE, ASSET_COUNT)            AS DOMINANT_LANGUAGE,
           MAX(ASSET_COUNT) / SUM(ASSET_COUNT)                 AS DOMINANT_SHARE
    FROM METRIC_VARIANT GROUP BY 1
)
-- deterministic id (hash of the normalized name) so resolutions survive a re-run
SELECT 'MET-' || UPPER(SUBSTR(MD5(FIELD_NAME_KEY), 1, 6)) AS METRIC_ID,
       g.*,
       (SELECT MODE(e.VALUE::TEXT)
          FROM CONFORMED.ASSET_FIELD f JOIN CONFORMED.ASSET_SIGNATURE s ON s.ASSET_ID = f.ASSET_ID,
               LATERAL FLATTEN(INPUT => s.ENTITIES) e
         WHERE f.FIELD_NAME_KEY = g.FIELD_NAME_KEY AND e.VALUE::TEXT LIKE 'FACT_%') AS PRIMARY_ENTITY,
       CASE WHEN VARIANT_COUNT = 1 THEN 'SINGLE_DEFINITION'
            WHEN DOMINANT_SHARE >= 0.8 THEN 'MINOR_VARIANCE'
            ELSE 'CONFLICTING' END                                         AS DEFINITION_STATUS
FROM g
WHERE ASSET_COUNT >= 2;

-- Resolution is a decision with a name on it. The copilot and the AI proposer
-- can write PROPOSED rows; only a human writes CERTIFIED.
CREATE TABLE IF NOT EXISTS METRIC_RESOLUTION (
    RESOLUTION_ID     NUMBER IDENTITY,
    METRIC_ID         TEXT,
    CANONICAL_NAME    TEXT,
    DEFINITION_SQL    TEXT,
    DEFINITION_TEXT   TEXT,
    EQUIVALENT_VARIANTS ARRAY,     -- expressions judged to mean the same thing
    DIVERGENT_VARIANTS  ARRAY,     -- expressions that are genuinely different (each needs a decision)
    PROPOSED_BY       TEXT,
    MODEL_USED        TEXT,
    RATIONALE         TEXT,
    STATUS            TEXT DEFAULT 'PROPOSED',   -- PROPOSED | CERTIFIED | REJECTED
    CERTIFIED_BY      TEXT,
    CERTIFIED_AT      TIMESTAMP_NTZ,
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------- SOURCE TO TARGET ------
CREATE OR REPLACE VIEW V_SOURCE_TO_TARGET_MAP AS
WITH x AS (
    SELECT ea.ENTITY_NAME, ea.ATTRIBUTE_NAME, ea.ATTRIBUTE_CLASS, ea.REFERENCING_ASSETS, ea.FIRST_WAVE_NEEDED,
           s.VALUE::TEXT AS SOURCE_COLUMN
    FROM ENTITY_ATTRIBUTE ea, LATERAL FLATTEN(INPUT => ea.SOURCE_COLUMNS) s
)
SELECT x.ENTITY_NAME, x.ATTRIBUTE_NAME, x.ATTRIBUTE_CLASS, TARGET_MODEL.ATTRIBUTE_TYPE(x.ATTRIBUTE_CLASS) AS TARGET_TYPE,
       x.SOURCE_COLUMN,
       SPLIT_PART(x.SOURCE_COLUMN, '.', 1) AS SOURCE_DATABASE,
       c.IS_DECOMMISSIONED, c.SYSTEM_FAMILY,
       CASE WHEN c.IS_DECOMMISSIONED THEN 'SOURCE_DECOMMISSIONED — map from the replacement system'
            WHEN c.SYSTEM_FAMILY ILIKE '%(hosted)%' THEN 'HOSTED_VENDOR — lineage only; map from your own system of record before the contract ends'
            WHEN SPLIT_PART(x.SOURCE_COLUMN, '.', 1) = 'SHAREPOINT' THEN 'SPREADSHEET — needs a system of record or a governed upload'
            ELSE 'MAPPED' END AS MAPPING_STATUS,
       x.REFERENCING_ASSETS, x.FIRST_WAVE_NEEDED
FROM x
LEFT JOIN INVENTORY.SOURCE_SYSTEM_CATALOG c
       ON c.SOURCE_DATABASE = SPLIT_PART(x.SOURCE_COLUMN, '.', 1) AND UPPER(c.SOURCE_TABLE) = UPPER(SPLIT_PART(x.SOURCE_COLUMN, '.', 3));

-- ------------------------------------------------------- BUILD BACKLOG ------
CREATE OR REPLACE VIEW V_BUILD_BACKLOG COPY GRANTS AS
SELECT e.FIRST_WAVE_NEEDED AS WAVE_NO, e.ENTITY_NAME, e.ENTITY_ROLE, e.SUBJECT_AREA, e.GRAIN, e.IS_SHARED,
       e.SURVIVING_ASSETS AS ASSETS_UNBLOCKED, e.EXEC_ASSETS, e.REGULATORY_ASSETS,
       (SELECT COUNT(*) FROM ENTITY_ATTRIBUTE a WHERE a.ENTITY_NAME = e.ENTITY_NAME) AS ATTRIBUTES,
       (SELECT COUNT(*) FROM METRIC m WHERE m.PRIMARY_ENTITY = e.ENTITY_NAME) AS METRICS,
       (SELECT COUNT(*) FROM METRIC m WHERE m.PRIMARY_ENTITY = e.ENTITY_NAME AND m.DEFINITION_STATUS = 'CONFLICTING') AS CONFLICTING_METRICS,
       ARRAY_SIZE(e.SOURCE_TABLES) AS SOURCE_TABLES, e.SOURCE_STATUS,
       -- indicative build effort: TO CONFIRM against the data team's velocity
       ROUND(8 + 0.5 * (SELECT COUNT(*) FROM ENTITY_ATTRIBUTE a WHERE a.ENTITY_NAME = e.ENTITY_NAME)
               + IFF(e.ENTITY_ROLE = 'FACT', 16, 4) + IFF(e.SOURCE_STATUS <> 'SOURCE_AVAILABLE', 24, 0)) AS BUILD_HOURS_INDICATIVE,
       ROW_NUMBER() OVER (ORDER BY e.FIRST_WAVE_NEEDED, e.IS_SHARED DESC, e.SURVIVING_ASSETS DESC, e.ENTITY_NAME) AS BUILD_ORDER  -- ENTITY_NAME breaks ties so the order is stable run to run
FROM ENTITY e;

CREATE OR REPLACE VIEW V_TARGET_MODEL_SUMMARY AS
SELECT (SELECT COUNT(*) FROM ENTITY)                                          AS ENTITIES,
       (SELECT COUNT(*) FROM ENTITY WHERE ENTITY_ROLE = 'FACT')               AS FACTS,
       (SELECT COUNT(*) FROM ENTITY WHERE ENTITY_ROLE = 'DIM')                AS DIMENSIONS,
       (SELECT COUNT(*) FROM ENTITY WHERE IS_SHARED)                          AS SHARED_ENTITIES,
       (SELECT COUNT(*) FROM ENTITY WHERE SOURCE_STATUS <> 'SOURCE_AVAILABLE') AS ENTITIES_NEEDING_A_SOURCE,
       (SELECT COUNT(*) FROM ENTITY_ATTRIBUTE)                                AS ATTRIBUTES,
       (SELECT COUNT(*) FROM METRIC)                                          AS METRICS,
       (SELECT COUNT(*) FROM METRIC WHERE DEFINITION_STATUS = 'CONFLICTING')  AS CONFLICTING_METRICS,
       (SELECT SUM(VARIANT_COUNT) FROM METRIC WHERE DEFINITION_STATUS <> 'SINGLE_DEFINITION') AS VARIANT_DEFINITIONS_TO_RECONCILE,
       (SELECT COUNT(*) FROM METRIC_RESOLUTION WHERE STATUS = 'CERTIFIED')    AS CERTIFIED_METRICS,
       (SELECT COUNT(DISTINCT SOURCE_COLUMN) FROM V_SOURCE_TO_TARGET_MAP)     AS SOURCE_COLUMNS_MAPPED,
       (SELECT COUNT(DISTINCT SOURCE_COLUMN) FROM V_SOURCE_TO_TARGET_MAP WHERE MAPPING_STATUS <> 'MAPPED') AS SOURCE_COLUMNS_NEEDING_DECISION;
