-- =============================================================================
-- APP — the workbench object and read grants
-- -----------------------------------------------------------------------------
-- The workbench reads views. Everything it shows is available to anyone with
-- a SQL client; the app is a way of reading the migration, not a second place
-- the migration lives.
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE WAREHOUSE BI_MOD_WH;
USE SCHEMA APP;

CREATE OR REPLACE STREAMLIT APP.BI_MODERNIZATION_WORKBENCH
    ROOT_LOCATION = '@BI_MODERNIZATION.APP.WORKBENCH_STAGE'
    MAIN_FILE = 'bi_app.py'
    QUERY_WAREHOUSE = BI_MOD_WH
    COMMENT = 'BI Rationalization & Migration Workbench — estate, usage, duplicates, dispositions with review gate, wave plan, target model, conversion, reconciliation, Migration Copilot.';

GRANT USAGE ON STREAMLIT APP.BI_MODERNIZATION_WORKBENCH TO ROLE PUBLIC;
GRANT USAGE ON DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE BI_MOD_WH TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS  IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT SELECT ON FUTURE TABLES IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT USAGE ON ALL FUNCTIONS  IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT USAGE ON ALL PROCEDURES IN DATABASE BI_MODERNIZATION TO ROLE PUBLIC;
GRANT SELECT ON SEMANTIC VIEW AI.SV_BI_ESTATE TO ROLE PUBLIC;
GRANT SELECT ON SEMANTIC VIEW AI.SV_MIGRATION_DELIVERY TO ROLE PUBLIC;
GRANT USAGE ON CORTEX SEARCH SERVICE AI.DEFINITION_SEARCH TO ROLE PUBLIC;
GRANT USAGE ON CORTEX SEARCH SERVICE AI.ESTATE_RECORD_SEARCH TO ROLE PUBLIC;
GRANT USAGE ON CORTEX SEARCH SERVICE AI.MIGRATION_REFERENCE_SEARCH TO ROLE PUBLIC;

-- The decision tables the workbench writes to.
GRANT INSERT, UPDATE ON TABLE RATIONALIZATION.DISPOSITION_REVIEW TO ROLE PUBLIC;
GRANT INSERT, UPDATE ON TABLE RATIONALIZATION.SCORING_POLICY TO ROLE PUBLIC;
GRANT INSERT, UPDATE ON TABLE TARGET_MODEL.METRIC_RESOLUTION TO ROLE PUBLIC;
GRANT UPDATE ON TABLE CONVERSION.FIELD_CONVERSION TO ROLE PUBLIC;
GRANT INSERT ON TABLE CONVERSION.ACCEPTANCE_SIGNOFF TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GOVERNANCE TO ROLE PUBLIC;
