-- =============================================================================
-- INVENTORY — tool-native landing tables
-- -----------------------------------------------------------------------------
-- Column names are the platforms' own. Nothing is renamed here on purpose: the
-- conform step is where a workbook, a report and a Webi document become the
-- same kind of thing, and that step should be visible, not hidden in a load.
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE SCHEMA INVENTORY;

-- ---- shared ----------------------------------------------------------------
CREATE OR REPLACE TABLE USER_DIRECTORY (
    USER_ID TEXT, EMAIL TEXT, DISPLAY_NAME TEXT, DEPARTMENT TEXT, TITLE TEXT,
    IS_EXECUTIVE BOOLEAN, IS_BI_DEVELOPER BOOLEAN, IS_ACTIVE BOOLEAN, TERMINATION_DATE DATE
) COMMENT = 'HR directory extract — who is an executive, who builds reports, who has left';

CREATE OR REPLACE TABLE SOURCE_SYSTEM_CATALOG (
    SOURCE_DATABASE TEXT, SOURCE_SCHEMA TEXT, SOURCE_TABLE TEXT, SUBJECT_AREA TEXT,
    ENTITY_ROLE TEXT, CONFORMED_ENTITY TEXT, GRAIN TEXT, IS_DECOMMISSIONED BOOLEAN,
    DECOMMISSIONED_DATE DATE, SYSTEM_FAMILY TEXT
) COMMENT = 'What each source table IS. Built with the client data team in week one; it is the bridge from lineage to the target model.';

-- ---- Tableau (REST + Metadata API) ----------------------------------------
CREATE OR REPLACE TABLE TABLEAU_WORKBOOKS (
    WORKBOOK_ID TEXT, NAME TEXT, PROJECT_NAME TEXT, PROJECT_PATH TEXT, OWNER_EMAIL TEXT,
    CREATED_AT TIMESTAMP_NTZ, UPDATED_AT TIMESTAMP_NTZ, CONTENT_URL TEXT, SIZE_MB NUMBER(10,1),
    TAGS TEXT, HAS_CERTIFIED_DS BOOLEAN, DESCRIPTION TEXT
);
CREATE OR REPLACE TABLE TABLEAU_VIEWS (
    VIEW_ID TEXT, WORKBOOK_ID TEXT, NAME TEXT, SHEET_TYPE TEXT,
    CREATED_AT TIMESTAMP_NTZ, UPDATED_AT TIMESTAMP_NTZ, LAYOUT_JSON TEXT
);
CREATE OR REPLACE TABLE TABLEAU_DATASOURCES (
    DATASOURCE_ID TEXT, WORKBOOK_ID TEXT, NAME TEXT, IS_PUBLISHED BOOLEAN, IS_CERTIFIED BOOLEAN,
    CONNECTION_TYPE TEXT, SERVER TEXT, DATABASE_NAME TEXT, SCHEMA_NAME TEXT, TABLE_NAMES TEXT,
    HAS_CUSTOM_SQL BOOLEAN, HAS_EXTRACT BOOLEAN, EXTRACT_REFRESH_SCHEDULE TEXT
);
CREATE OR REPLACE TABLE TABLEAU_CALCULATED_FIELDS (
    FIELD_ID TEXT, WORKBOOK_ID TEXT, DATASOURCE_ID TEXT, NAME TEXT, FORMULA TEXT,
    DATA_TYPE TEXT, ROLE TEXT, IS_LOD BOOLEAN, IS_TABLE_CALC BOOLEAN, REFERENCED_FIELDS TEXT
);
CREATE OR REPLACE TABLE TABLEAU_FIELD_LINEAGE (
    DATASOURCE_ID TEXT, FIELD_NAME TEXT, UPSTREAM_DATABASE TEXT, UPSTREAM_SCHEMA TEXT,
    UPSTREAM_TABLE TEXT, UPSTREAM_COLUMN TEXT
);
CREATE OR REPLACE TABLE TABLEAU_VIEWS_STATS (
    STAT_DATE DATE, VIEW_ID TEXT, WORKBOOK_ID TEXT, USER_EMAIL TEXT, SITE_ROLE TEXT, NB_VIEWS NUMBER
);
CREATE OR REPLACE TABLE TABLEAU_SUBSCRIPTIONS (
    SUBSCRIPTION_ID TEXT, WORKBOOK_ID TEXT, VIEW_ID TEXT, USER_EMAIL TEXT, SCHEDULE TEXT,
    FORMAT TEXT, IS_ENABLED BOOLEAN
);
CREATE OR REPLACE TABLE TABLEAU_EXTRACT_REFRESHES (
    RUN_ID TEXT, WORKBOOK_ID TEXT, STARTED_AT TIMESTAMP_NTZ, STATUS TEXT, DURATION_SEC NUMBER
);

-- ---- Power BI (admin scanner + activity events) ----------------------------
CREATE OR REPLACE TABLE PBI_WORKSPACES (
    WORKSPACE_ID TEXT, NAME TEXT, TYPE TEXT, STATE TEXT, IS_ON_DEDICATED_CAPACITY BOOLEAN, SEQ NUMBER
);
CREATE OR REPLACE TABLE PBI_REPORTS (
    REPORT_ID TEXT, WORKSPACE_ID TEXT, NAME TEXT, DATASET_ID TEXT, CREATED_BY TEXT,
    CREATED_DATETIME TIMESTAMP_NTZ, MODIFIED_DATETIME TIMESTAMP_NTZ, REPORT_TYPE TEXT, WEB_URL TEXT
);
CREATE OR REPLACE TABLE PBI_REPORT_PAGES (
    REPORT_ID TEXT, PAGE_NAME TEXT, DISPLAY_NAME TEXT, VISUAL_COUNT NUMBER, VISUAL_TYPES TEXT, LAYOUT_JSON TEXT
);
CREATE OR REPLACE TABLE PBI_DATASETS (
    DATASET_ID TEXT, WORKSPACE_ID TEXT, NAME TEXT, CONFIGURED_BY TEXT, IS_REFRESHABLE BOOLEAN,
    REFRESH_SCHEDULE TEXT, STORAGE_MODE TEXT, ENDORSEMENT TEXT, CREATED_DATE TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE PBI_DATASET_TABLES (
    DATASET_ID TEXT, TABLE_NAME TEXT, SOURCE_TYPE TEXT, SOURCE_EXPRESSION TEXT, COLUMN_COUNT NUMBER,
    SOURCE_DATABASE TEXT, SOURCE_SCHEMA TEXT, SOURCE_TABLE TEXT, COLUMNS_JSON TEXT
);
CREATE OR REPLACE TABLE PBI_MEASURES (
    DATASET_ID TEXT, TABLE_NAME TEXT, MEASURE_NAME TEXT, EXPRESSION TEXT, IS_HIDDEN BOOLEAN, KIND TEXT
);
CREATE OR REPLACE TABLE PBI_ACTIVITY_EVENTS (
    EVENT_ID TEXT, ACTIVITY_DATETIME TIMESTAMP_NTZ, ACTIVITY TEXT, USER_ID TEXT, REPORT_ID TEXT,
    WORKSPACE_ID TEXT, DATASET_ID TEXT, DISTRIBUTION_METHOD TEXT, CONSUMPTION_METHOD TEXT
);
CREATE OR REPLACE TABLE PBI_REFRESH_HISTORY (
    DATASET_ID TEXT, START_TIME TIMESTAMP_NTZ, END_TIME TIMESTAMP_NTZ, STATUS TEXT
);
CREATE OR REPLACE TABLE PBI_SUBSCRIPTIONS (
    SUBSCRIPTION_ID TEXT, REPORT_ID TEXT, USER_EMAIL TEXT, FREQUENCY TEXT, IS_ENABLED BOOLEAN
);

-- ---- SAP BusinessObjects (CMS InfoObjects + Auditing) ----------------------
CREATE OR REPLACE TABLE BO_UNIVERSES (
    SI_ID NUMBER, SI_CUID TEXT, SI_NAME TEXT, FOLDER_PATH TEXT, UNIVERSE_TYPE TEXT, CONNECTION_NAME TEXT,
    DB_TYPE TEXT, DATABASE_NAME TEXT, LAST_MODIFIED TIMESTAMP_NTZ, OWNER TEXT
);
CREATE OR REPLACE TABLE BO_UNIVERSE_OBJECTS (
    UNIVERSE_SI_ID NUMBER, CLASS_NAME TEXT, OBJECT_NAME TEXT, OBJECT_TYPE TEXT, SELECT_SQL TEXT,
    WHERE_SQL TEXT, AGGREGATE_FUNCTION TEXT
);
CREATE OR REPLACE TABLE BO_WEBI_DOCUMENTS (
    SI_ID NUMBER, SI_CUID TEXT, DOC_KEY TEXT, SI_NAME TEXT, FOLDER_PATH TEXT, SI_OWNER TEXT,
    SI_CREATION_TIME TIMESTAMP_NTZ, SI_UPDATE_TS TIMESTAMP_NTZ, UNIVERSE_IDS TEXT, IS_SCHEDULED BOOLEAN,
    INSTANCE_COUNT NUMBER, SI_KIND TEXT, SIZE_MB NUMBER(10,1)
);
CREATE OR REPLACE TABLE BO_WEBI_QUERIES (
    DOC_SI_ID NUMBER, QUERY_NAME TEXT, UNIVERSE_SI_ID NUMBER, RESULT_OBJECTS TEXT, FILTER_OBJECTS TEXT,
    HAS_PROMPT BOOLEAN, HAS_CUSTOM_SQL BOOLEAN, CUSTOM_SQL TEXT
);
CREATE OR REPLACE TABLE BO_WEBI_VARIABLES (
    DOC_SI_ID NUMBER, VARIABLE_NAME TEXT, FORMULA TEXT, QUALIFICATION TEXT
);
CREATE OR REPLACE TABLE BO_REPORT_ELEMENTS (
    DOC_SI_ID NUMBER, REPORT_TAB TEXT, ELEMENT_NAME TEXT, ELEMENT_TYPE TEXT, DIMENSIONS TEXT, MEASURES TEXT, FILTERS TEXT
);
CREATE OR REPLACE TABLE BO_AUDIT_EVENTS (
    EVENT_ID TEXT, START_TIME TIMESTAMP_NTZ, EVENT_TYPE TEXT, USER_NAME TEXT, OBJECT_SI_ID NUMBER,
    OBJECT_TYPE TEXT, DURATION_MS NUMBER
);
CREATE OR REPLACE TABLE BO_SCHEDULES (
    SCHEDULE_ID TEXT, DOC_SI_ID NUMBER, RECURRENCE TEXT, DESTINATION TEXT, RECIPIENT_COUNT NUMBER,
    LAST_RUN_STATUS TEXT, LAST_RUN_TIME TIMESTAMP_NTZ
);

-- ---- MedeAnalytics (hosted platform — admin-console exports; shape ILLUSTRATIVE,
-- confirm per customer: there is no public metadata/usage API) -------------
CREATE OR REPLACE TABLE MEDE_REPORTS (
    REPORT_ID TEXT, REPORT_NAME TEXT, MODULE TEXT, REPORT_TYPE TEXT, FOLDER_PATH TEXT, OWNER TEXT,
    CREATED_DATE TIMESTAMP_NTZ, MODIFIED_DATE TIMESTAMP_NTZ, FORMAT TEXT, DATA_DOMAINS TEXT, IS_SCHEDULED BOOLEAN
);
CREATE OR REPLACE TABLE MEDE_REPORT_FIELDS (
    REPORT_ID TEXT, FIELD_NAME TEXT, FIELD_KIND TEXT, IS_VENDOR_DEFINED BOOLEAN, DEFINITION TEXT, DATA_DOMAIN TEXT, DOMAIN_COLUMN TEXT
);
CREATE OR REPLACE TABLE MEDE_REPORT_SECTIONS (
    REPORT_ID TEXT, SECTION_NO NUMBER, SECTION_NAME TEXT, VISUAL_TYPE TEXT, DIMENSIONS TEXT, MEASURES TEXT, FILTERS TEXT, HAS_PROMPT BOOLEAN
);
CREATE OR REPLACE TABLE MEDE_USER_ACTIVITY (
    ACTIVITY_TIME TIMESTAMP_NTZ, USER_EMAIL TEXT, REPORT_ID TEXT, ACTION TEXT
);
CREATE OR REPLACE TABLE MEDE_DELIVERIES (
    DELIVERY_ID TEXT, REPORT_ID TEXT, RECIPIENT_EMAIL TEXT, FREQUENCY TEXT, FORMAT TEXT, IS_ACTIVE BOOLEAN
);

-- Generator truth — used ONLY by the verification script to measure the rule
-- engine against what was planted. Never read by a finding.
CREATE OR REPLACE TABLE _GENERATOR_TRUTH (
    ASSET_ID TEXT, TOOL TEXT, TITLE TEXT, TEMPLATE TEXT, CLUSTER_ID TEXT, VARIANT_KIND TEXT, LIFECYCLE TEXT,
    POPULARITY NUMBER(6,2), COMPLEXITY NUMBER, COMPLIANCE BOOLEAN, PERSONAL BOOLEAN, BROKEN BOOLEAN,
    SUBSCRIBED BOOLEAN, SCHEDULED BOOLEAN, SUB_ONLY BOOLEAN, AUDIENCE TEXT, SUBJECT_AREA TEXT
);
