-- =============================================================================
-- INVENTORY — load the extracts (files were PUT to @INVENTORY.LANDING by build_all)
-- =============================================================================
USE DATABASE BI_MODERNIZATION;
USE SCHEMA INVENTORY;

COPY INTO USER_DIRECTORY          FROM @LANDING/user_directory.csv          FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO SOURCE_SYSTEM_CATALOG   FROM @LANDING/source_system_catalog.csv   FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_WORKBOOKS       FROM @LANDING/tableau_workbooks.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_VIEWS           FROM @LANDING/tableau_views.csv           FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_DATASOURCES     FROM @LANDING/tableau_datasources.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_CALCULATED_FIELDS FROM @LANDING/tableau_calculated_fields.csv FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_FIELD_LINEAGE   FROM @LANDING/tableau_field_lineage.csv   FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_VIEWS_STATS     FROM @LANDING/tableau_views_stats.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_SUBSCRIPTIONS   FROM @LANDING/tableau_subscriptions.csv   FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO TABLEAU_EXTRACT_REFRESHES FROM @LANDING/tableau_extract_refreshes.csv FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_WORKSPACES          FROM @LANDING/pbi_workspaces.csv          FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_REPORTS             FROM @LANDING/pbi_reports.csv             FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_REPORT_PAGES        FROM @LANDING/pbi_report_pages.csv        FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_DATASETS            FROM @LANDING/pbi_datasets.csv            FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_DATASET_TABLES      FROM @LANDING/pbi_dataset_tables.csv      FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_MEASURES            FROM @LANDING/pbi_measures.csv            FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_ACTIVITY_EVENTS     FROM @LANDING/pbi_activity_events.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_REFRESH_HISTORY     FROM @LANDING/pbi_refresh_history.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO PBI_SUBSCRIPTIONS       FROM @LANDING/pbi_subscriptions.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_UNIVERSES            FROM @LANDING/bo_universes.csv            FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_UNIVERSE_OBJECTS     FROM @LANDING/bo_universe_objects.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_WEBI_DOCUMENTS       FROM @LANDING/bo_webi_documents.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_WEBI_QUERIES         FROM @LANDING/bo_webi_queries.csv         FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_WEBI_VARIABLES       FROM @LANDING/bo_webi_variables.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_REPORT_ELEMENTS      FROM @LANDING/bo_report_elements.csv      FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_AUDIT_EVENTS         FROM @LANDING/bo_audit_events.csv         FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO BO_SCHEDULES            FROM @LANDING/bo_schedules.csv            FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO MEDE_REPORTS             FROM @LANDING/mede_reports.csv             FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO MEDE_REPORT_FIELDS       FROM @LANDING/mede_report_fields.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO MEDE_REPORT_SECTIONS     FROM @LANDING/mede_report_sections.csv     FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO MEDE_USER_ACTIVITY       FROM @LANDING/mede_user_activity.csv       FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO MEDE_DELIVERIES          FROM @LANDING/mede_deliveries.csv          FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;
COPY INTO _GENERATOR_TRUTH        FROM @LANDING/_truth_assets.csv           FILE_FORMAT = CSV_EXTRACT ON_ERROR = ABORT_STATEMENT;

SELECT 'USER_DIRECTORY' T, COUNT(*) N FROM USER_DIRECTORY
UNION ALL SELECT 'TABLEAU_WORKBOOKS', COUNT(*) FROM TABLEAU_WORKBOOKS
UNION ALL SELECT 'PBI_REPORTS', COUNT(*) FROM PBI_REPORTS
UNION ALL SELECT 'BO_WEBI_DOCUMENTS', COUNT(*) FROM BO_WEBI_DOCUMENTS
UNION ALL SELECT 'TABLEAU_VIEWS_STATS', COUNT(*) FROM TABLEAU_VIEWS_STATS
UNION ALL SELECT 'PBI_ACTIVITY_EVENTS', COUNT(*) FROM PBI_ACTIVITY_EVENTS
UNION ALL SELECT 'BO_AUDIT_EVENTS', COUNT(*) FROM BO_AUDIT_EVENTS
UNION ALL SELECT 'MEDE_REPORTS', COUNT(*) FROM MEDE_REPORTS
UNION ALL SELECT 'MEDE_USER_ACTIVITY', COUNT(*) FROM MEDE_USER_ACTIVITY;
